services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_SERVER=db
    volumes:
      - ./:/app

# Add this section at root level (same indentation as 'services')
volumes:
  postgres_data: